<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>

  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\IronHive.Flux\IronHive.Flux.csproj" />
    <ProjectReference Include="..\..\src\IronHive.Flux.WebLookup\IronHive.Flux.WebLookup.csproj" />
    <ProjectReference Include="..\..\src\IronHive.Tools.WebLookup\IronHive.Tools.WebLookup.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.Testing.Extensions.HangDump" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

</Project>
